In [1]:
# Recursive Feature Elimination
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [2]:
# load the dataset
df = pd.read_csv('../csv_files/p3feature-selection.csv', index_col=0)
df.head()

C1        C4       C6p        C7       C5p       T4p       T3p  \
0  0.458312  0.630418  0.788811  0.207673  0.471242  0.534307  0.617569   
1  1.000000  0.384735  0.000000  0.147494  1.000000  0.545709  0.521720   
2  0.327366  0.582011  0.000000  0.078383  0.406077  0.524798  0.622040   
3  0.814322  0.578004  0.000000  0.084319  0.396940  0.268780  0.694834   
4  0.286445  0.259982  0.529150  0.729255  0.453073  0.394649  0.424900   

        T5p       S1p       S2p       S3p   C2  C3p  Industry_Bins  Y1  Y2  
0  0.567375  0.462525  0.729701  0.478776  1.0    0              1   0   1  
1  0.489104  0.271483  0.817120  0.474754  0.0    1              1   1   0  
2  0.773408  1.000000  0.569904  0.514761  1.0    1              1   1   0  
3  0.769738  1.000000  0.621831  0.660248  1.0    1              1   1   1  
4  0.411101  0.420367  0.769835  0.504014  1.0    0              3   0   1

In [3]:
df.dtypes

C1               float64
C4               float64
C6p              float64
C7               float64
C5p              float64
T4p              float64
T3p              float64
T5p              float64
S1p              float64
S2p              float64
S3p              float64
C2               float64
C3p                int64
Industry_Bins      int64
Y1                 int64
Y2                 int64
dtype: object

In [4]:
array = df.values
X = array[:,:-2] #features
Y = array[:,-2] #target

In [5]:
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(X, Y)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False  True False False False  True False False  True False False
 False False]
[ 9  4  1  5 12  2  1  3  6  1  8 11 10  7]


/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default so

In [6]:
for i in range(1, len(X[0])+1):
    print(i)
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes
    rfe = RFE(model, i)
    rfe = rfe.fit(X, Y)
    # summarize the selection of the attributes
    print('Model with the best', i, 'features')
    print(rfe.support_)
    print(rfe.ranking_)

/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default so

1
Model with the best 1 features
[False False  True False False False False False False False False False
 False False]
[11  6  1  7 14  4  3  5  8  2 10 13 12  9]
2
Model with the best 2 features
[False False  True False False False False False False  True False False
 False False]
[10  5  1  6 13  3  2  4  7  1  9 12 11  8]
3
Model with the best 3 features
[False False  True False False False  True False False  True False False
 False False]
[ 9  4  1  5 12  2  1  3  6  1  8 11 10  7]
4
Model with the best 4 features
[False False  True False False  True  True False False  True False False
 False False]
[ 8  3  1  4 11  1  1  2  5  1  7 10  9  6]
5
Model with the best 5 features
[False False  True False False  True  True  True False  True False False
 False False]
[ 7  2  1  3 10  1  1  1  4  1  6  9  8  5]
6
Model with the best 6 features
[False  True  True False False  True  True  True False  True False False
 False False]
[6 1 1 2 9 1 1 1 3 1 5 8 7 4]
7
Model with the best 7 featur

/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default so

Model with the best 8 features
[False  True  True  True False  True  True  True  True  True False False
 False False]
[4 1 1 1 7 1 1 1 1 1 3 6 5 2]
9
Model with the best 9 features
[False  True  True  True False  True  True  True  True  True False False
 False  True]
[3 1 1 1 6 1 1 1 1 1 2 5 4 1]
10
Model with the best 10 features
[False  True  True  True False  True  True  True  True  True  True False
 False  True]
[2 1 1 1 5 1 1 1 1 1 1 4 3 1]
11
Model with the best 11 features
[ True  True  True  True False  True  True  True  True  True  True False
 False  True]
[1 1 1 1 4 1 1 1 1 1 1 3 2 1]
12
Model with the best 12 features
[ True  True  True  True False  True  True  True  True  True  True False
  True  True]
[1 1 1 1 3 1 1 1 1 1 1 2 1 1]
13
Model with the best 13 features
[ True  True  True  True False  True  True  True  True  True  True  True
  True  True]
[1 1 1 1 2 1 1 1 1 1 1 1 1 1]
14
Model with the best 14 features
[ True  True  True  True  True  True  True  True  True  Tru

/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/jupyter-kclarke/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default so