In [6]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [7]:
# load the dataset
df = pd.read_csv('../csv_files/p2feature-selection.csv', index_col=0)
df.head()

C1        C4       C6p        C7       C5p       T4p       T3p  \
0  0.030756  0.669243  1.282356 -0.477847  0.056127  0.168742  0.174345   
1  1.279824 -0.643726 -0.759933 -0.789310  2.434275  0.229402  0.099767   
2 -0.431183  0.410546 -0.759933 -1.277684 -0.231083  0.118150  0.177807   
3  0.907828  0.389135 -0.759933 -1.226569 -0.274697 -1.243939  0.233959   
4 -0.603838 -1.310426  1.027869  1.026514 -0.020075 -0.574282  0.023718   

        T5p       S1p       S2p       S3p   C2  C3p  Industry_Bins  Y1  Y2  
0  0.310826 -0.146970  0.165628 -0.128062  1.0    0              1   0   1  
1 -0.016168 -1.240880  0.781633 -0.147676  0.0    1              1   1   0  
2  1.107680  2.767209 -0.974221  0.044649  1.0    1              1   1   0  
3  1.094210  2.091907 -0.602916  0.697829  1.0    1              1   1   1  
4 -0.357465 -0.364704  0.449384 -0.006421  1.0    0              3   0   1

In [14]:
#Converting the datagrame into the correct arrays to make filtering easier 
array = df.values
X = abs(array[:,:-2]) #features
Y1 = array[:,-2]
Y2 = array[:,-1]

In [15]:
# Feature selection for Target 1
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y1)

# Summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(X)
# Summarize selected features
print(features[0:5,:])

[7.417e-01 1.080e+00 2.760e+01 7.327e+00 4.532e-01 1.434e-01 2.399e+00
 1.720e-02 2.992e-01 4.989e-02 6.144e-01 4.750e-01 4.831e+00 2.006e+00]
[[1.282 0.478 0.174 0.   ]
 [0.76  0.789 0.1   1.   ]
 [0.76  1.278 0.178 1.   ]
 [0.76  1.227 0.234 1.   ]
 [1.028 1.027 0.024 0.   ]]


In [16]:
# Feature selection for Target 2
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y2)

# Summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(X)
# Summarize selected features
print(features[0:5,:])

[2.542e-04 8.318e-02 3.963e+00 1.116e-02 2.516e+00 5.053e-01 1.054e+01
 5.453e+00 1.070e+00 9.118e-01 1.455e+00 1.834e-01 4.211e-01 2.095e+00]
[[1.282 0.056 0.174 0.311]
 [0.76  2.434 0.1   0.016]
 [0.76  0.231 0.178 1.108]
 [0.76  0.275 0.234 1.094]
 [1.028 0.02  0.024 0.357]]
