In [1]:
# Recursive Feature Elimination
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [2]:
# load the dataset
df = pd.read_csv('../csv_files/p2evalcode.csv', index_col=0)
df.head()

C1        C4        C6        C7       C5p       T4p       T3p  \
0  0.013297  0.671107  0.336688 -0.561408  0.054797  0.168664  0.385146   
1  1.259277 -0.641901 -1.649356 -0.861441  2.432764  0.229323  0.151570   
2 -0.447500  0.412402 -0.667998 -1.331894 -0.232390  0.118072  0.396011   
3  0.888201  0.390990 -0.808871 -1.282655 -0.276002 -1.244015  0.572529   
4 -0.619728 -1.308620  0.001567  0.887747 -0.021399 -0.574359 -0.085643   

        T5p       S1p       S2p       S3p   C2  C3p  Industry_Bins  Y1  Y2  
0  0.310576 -0.147291  0.165044 -0.128181  1.0    0              1   0   1  
1 -0.016410 -1.241195  0.781034 -0.147795  0.0    1              1   1   0  
2  1.107408  2.766871 -0.974778  0.044531  1.0    1              1   1   0  
3  1.093939  2.091573 -0.603481  0.697712  1.0    1              1   1   1  
4 -0.357698 -0.365024  0.448793 -0.006539  1.0    0              3   0   1

In [3]:
df = df.drop(labels='C2', axis=1)
df.head()

C1        C4        C6        C7       C5p       T4p       T3p  \
0  0.013297  0.671107  0.336688 -0.561408  0.054797  0.168664  0.385146   
1  1.259277 -0.641901 -1.649356 -0.861441  2.432764  0.229323  0.151570   
2 -0.447500  0.412402 -0.667998 -1.331894 -0.232390  0.118072  0.396011   
3  0.888201  0.390990 -0.808871 -1.282655 -0.276002 -1.244015  0.572529   
4 -0.619728 -1.308620  0.001567  0.887747 -0.021399 -0.574359 -0.085643   

        T5p       S1p       S2p       S3p  C3p  Industry_Bins  Y1  Y2  
0  0.310576 -0.147291  0.165044 -0.128181    0              1   0   1  
1 -0.016410 -1.241195  0.781034 -0.147795    1              1   1   0  
2  1.107408  2.766871 -0.974778  0.044531    1              1   1   0  
3  1.093939  2.091573 -0.603481  0.697712    1              1   1   1  
4 -0.357698 -0.365024  0.448793 -0.006539    0              3   0   1

In [4]:
df.dtypes

C1               float64
C4               float64
C6               float64
C7               float64
C5p              float64
T4p              float64
T3p              float64
T5p              float64
S1p              float64
S2p              float64
S3p              float64
C3p                int64
Industry_Bins      int64
Y1                 int64
Y2                 int64
dtype: object

In [5]:
array = df.values
X = array[:,:-2] #features
Y = array[:,-2] #target - y1

In [6]:
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(X, Y)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False False False False  True False False False  True False  True
 False]
[ 7  4  2 11  3  1  9  8  6  1 10  1  5]


In [7]:
for i in range(1, len(X[0])+1):
    print(i)
    # create a base classifier used to evaluate a subset of attributes
    model = LogisticRegression()
    # create the RFE model and select 3 attributes
    rfe = RFE(model, i)
    rfe = rfe.fit(X, Y)
    # summarize the selection of the attributes
    print('Model with the best', i, 'features')
    print(rfe.support_)
    print(rfe.ranking_)

1
Model with the best 1 features
[False False False False False False False False False False False  True
 False]
[ 9  6  4 13  5  3 11 10  8  2 12  1  7]
2
Model with the best 2 features
[False False False False False False False False False  True False  True
 False]
[ 8  5  3 12  4  2 10  9  7  1 11  1  6]
3
Model with the best 3 features
[False False False False False  True False False False  True False  True
 False]
[ 7  4  2 11  3  1  9  8  6  1 10  1  5]
4
Model with the best 4 features
[False False  True False False  True False False False  True False  True
 False]
[ 6  3  1 10  2  1  8  7  5  1  9  1  4]
5
Model with the best 5 features
[False False  True False  True  True False False False  True False  True
 False]
[5 2 1 9 1 1 7 6 4 1 8 1 3]
6
Model with the best 6 features
[False  True  True False  True  True False False False  True False  True
 False]
[4 1 1 8 1 1 6 5 3 1 7 1 2]
7
Model with the best 7 features
[False  True  True False  True  True False False False  True Fa